# Nama file: .github/workflows/cordova-build.yml
name: Cordova Build Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Langkah 1: Minta token dengan action yang sudah disederhanakan
      - name: Request short-lived GHCR token
        id: get_token_step  # Beri ID pada langkah ini
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.inputs.appBaseUrl }}
          buildId: ${{ github.event.inputs.buildId }}
          buildToken: ${{ github.event.inputs.buildToken }}

      # Langkah 2: Login ke GHCR (HAMPIR SAMA, HANYA MENGUBAH CARA MENGAMBIL PASSWORD)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          # Ambil password dari output action di Langkah 1
          password: ${{ steps.get_token_step.outputs.token }}

      # Langkah 3: Jalankan Build Engine (TIDAK ADA PERUBAHAN SAMA SEKALI)
      - name: Build Cordova Project via Secure Engine
        run: |
          docker run --rm \
            -e INPUT_APPBASEURL=${{ github.event.inputs.appBaseUrl }} \
            -e INPUT_BUILDID=${{ github.event.inputs.buildId }} \
            -e INPUT_BUILDTOKEN=${{ github.event.inputs.buildToken }} \
            -e GITHUB_SERVER_URL=${{ github.server_url }} \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e GITHUB_RUN_ID=${{ github.run_id }} \
            ghcr.io/swaplab-engine/cordova-build-engine:main
