# File workflow pengguna (tetap sama, bersih dan sederhana)

# Nama file: .github/workflows/cordova-build.yml
name: Cordova Build Service

on:
  workflow_dispatch:
    inputs:
      appBaseUrl:
        required: true
      buildId:
        required: true
      buildToken:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Cordova Project via Secure Engine
        uses: swaplab-engine/cordova-build-engine@main
        with:
          appBaseUrl: ${{ github.event.inputs.appBaseUrl }}
          buildId: ${{ github.event.inputs.buildId }}
          buildToken: ${{ github.event.inputs.buildToken }}
